### ISSUE TITLE
Current release flagged as virus by Windows 10 + Chrome

### ISSUE THREAD

**Issue by Ketris** [PhantomGamers/EnableNewSteamFriendsSkin#1]
Title.

**Comment by PhantomGamers** [comment]
Yeah I'm noticing this too, even the version I had on my PC got flagged when I went to run it. Must have just been added.

I think someone must have manually reported the exe, because I rebuilt it and it's not being detected anymore. So that rules out heuristics. I reuploaded the exe but I will likely need a better solution in the future.

**Comment by LavenderTheGreat** [comment]
On windows it's being blocked by Smart Screen, which blocks on the basis of download amounts as far as I know, give or take some other information, so it's probably because it hasn't been downloaded much.

**Comment by PhantomGamers** [comment]
It was actually windows defender flagging it, not just smart screen.

**Comment by Ketris** [comment]
It's a bit strange that Microsoft literally has the source code on their Git servers yet claimed the executable was malicious.
